spring.application.name=mintUp
# ========================================
# Spring Profile
# ========================================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


# ========================================
# Actuator
# ========================================

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always