# ========================================
# Local
# ========================================

server.port=8080

spring.application.name=my-app

# Database
# ========================================
spring.datasource.url=jdbc:mysql://localhost:3306/mintUp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=uv353082!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# MyBatis
# ========================================
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.badminton.mintup.domain
mybatis.configuration.map-underscore-to-camel-case=true